### ISSUE TITLE
Attributes make error with SkeletonLayout

### ISSUE THREAD

**Issue by UltramanTIGA** [Faltenreich/SkeletonLayout#2]
Hi,man! I'm here again.
I found a error that make crash.
When skeletonLayout is defined with custom attributes in xml layout, it will make app crash! Just like below:

```
<com.faltenreich.skeletonlayout.SkeletonLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/skeletonLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:padding="@dimen/margin"
    app:cornerRadius="10dp"          <!- Add this line -->
>

    <include layout="@layout/list_item"/>

</com.faltenreich.skeletonlayout.SkeletonLayout>
```

When I remove the line "app:cornerRadius="10dp" ",it works well.
When I add this line,it makes crash.The log is:

```
android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.faltenreich.skeletonlayout.SkeletonLayout
    Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.faltenreich.skeletonlayout.SkeletonLayout
    Caused by: java.lang.reflect.InvocationTargetException
```

**Comment by Faltenreich** [comment]
Hello friend,

this was indeed a bug within the library due to obtaining the dimension resource for "cornerRadius" with getFloat instead of getDimensionPixelSize (see [7626b8d4d4ff6269aab70ff56fcb92dc1f7f2ce0](https://github.com/Faltenreich/SkeletonLayout/commit/7626b8d4d4ff6269aab70ff56fcb92dc1f7f2ce0#diff-3a1b076c6a1ef08c51db0cc57b1d8dc3)).

I corrected this behavior and additionally renamed the attribute from "cornerRadius" to "maskCornerRadius" in order to match the rest of the api. With version 1.0.1 the problem should be fixed.

Thanks again and have a nice day!

**Comment by Faltenreich** [comment]
After some delays on JCenter, version 1.0.1 is online which fixes this issue. Thanks again and best regards!
