### ISSUE TITLE
migrate to maven central

### ISSUE THREAD

**Issue by jeremyrempel** [Faltenreich/SkeletonLayout#29]
jcenter will be sunset on May 1, 2020 [announcement](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

**Comment by Faltenreich** [comment]
Thank you for your hint! SkeletonLayout will be moved to another repository before May. Currently I am researching and evaluating different repositories before deciding where to move this library.

**Comment by eygraber** [comment]
Any update on this?

**Comment by Faltenreich** [comment]
@eygraber JCenter will allow downloads of existing artifacts until February 1, 2022. This means that until then everyone should be able to use SkeletonLayout as usual and without any problem. Meanwhile I will search for a new repository and then move this library before February 1, 2022 arrives (or a new update of SkeletonLayout). The current plan is to move to MavenCentral, so existing clients do not have to change anything at all while silently migrating to the new repository due to MavenCentral being already included in most projects by default.

**Comment by eygraber** [comment]
I can submit a PR that will make the project ready to deploy to maven central. All you would have to do is set up your account. 

Is that ok with you?

**Comment by Faltenreich** [comment]
@eygraber That sounds simply awesome! I will do as you advised and get back in touch with you the next days when my work schedule allows it. Thank you in advance and best regards!

**Comment by IrhamMaulani** [comment]
Hi, any update on this?

**Comment by Faltenreich** [comment]
@IrhamMaulani I am currently working on pushing this library to MavenCentral with the help of @eygraber.

@eygraber I merged your pull request and receive the following error when publishing the artifacts via GitHub action: 

```
Run ./release
  ./release
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME_11.0.11_x64: /opt/hostedtoolcache/jdk/11.0.11/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.11/x64
    JAVA_HOME_11_0_11_X64: /opt/hostedtoolcache/jdk/11.0.11/x64
    ORG_GRADLE_PROJECT_mavenCentralUsername: ***
    ORG_GRADLE_PROJECT_mavenCentralPassword: ***
    ORG_GRADLE_PROJECT_signingInMemoryKey: ***
./release: 3: ./gradlew: Permission denied
Error: Process completed with exit code 126.
```

I followed the steps from https://github.com/vanniktech/gradle-maven-publish-plugin.

First I registered to the Nexus Repository which seems succesful:

<img width="477" alt="Unbenannt" src="https://user-images.githubusercontent.com/7239950/124383269-e3029080-dccb-11eb-94b7-cedd932aa0a8.PNG">

Then I added the secrets for GitHub Actions:

- SONATYPE_NEXUS_USERNAME: My user name for https://s01.oss.sonatype.org
- SONATYPE_NEXUS_PASSWORD: My password for https://s01.oss.sonatype.org
- ARTIFACT_SIGNING_PRIVATE_KEY: I created a GPG Key like described here and exported its full RSA-4096 Key via `gpg --armor --export` into a ASCII Armored Key which will then be used for signingInMemoryKe (Attention: I used the full key instead of the 8-digit public key which would be used for the keyId - is this correct?).

Lastly I merged your pull request and executed the GitHub action which lead to the error described above.

**Comment by Faltenreich** [comment]
@eygraber PR #34 looks better, but this time fails with `java.io.IOException: secret key ring doesn't start with secret key tag: tag 0x6`. There seems to be something wrong the GPG Key which I exported as described above:
```
ARTIFACT_SIGNING_PRIVATE_KEY: I created a GPG Key like described here and exported its full RSA-4096 Key via gpg --armor --export into a ASCII Armored Key which will then be used for signingInMemoryKe (Attention: I used the full key instead of the 8-digit public key which would be used for the keyId - is this correct?).
```
Is there something wrong with this?

**Comment by eygraber** [comment]
Looks like you need to use `export-secret-keys`

http://www.spywarewarrior.com/uiuc/gpg/gpg-com-4.htm#4-2c

You can update the secret on GitHub and then rerun the failed job.

**Comment by Faltenreich** [comment]
Now that private matters have settled and I have more time to spare, I was finally able to upload this library to MavenCentral manually by following this guide: [Publishing your first Android library to MavenCentral](https://www.waseefakhtar.com/android/publishing-your-first-android-library-to-mavencentral). 

SkeletonLayout 4.0.0 can now be used through mavenCentral() instead of jcenter()!

I will adjust documentation after the project has been indexed on Maven. Additionally before publishing the next version, I will fix the GitHub Action, so that I do not have to publish manually every time. 

Thank you all for supporting me on this case, especially @eygraber whose help is much appreciated!
