### ISSUE TITLE
background color not showing

### ISSUE THREAD

**Issue by e4basil** [Faltenreich/SkeletonLayout#3]
I have recycler view items contains border colour when applying to SkeletonLayout it removes

**Comment by Faltenreich** [comment]
SkeletonLayout iterates through all ViewGroups and Views in order to apply a shader to the bounds of every child View. Any border- or background color gets ignored in order to create a consistent skeleton layout. ViewGroups themselves are ignored, too, because masking them would obscure their child Views. 

I think that the behavior you see is intended or otherwise I may misunderstand your question. In that case, some example images would be very helpful.

**Comment by e4basil** [comment]
![untitled](https://user-images.githubusercontent.com/9576366/48997762-04478b80-f177-11e8-8101-6f48bfee67e8.png)

i want recyclerview border like this, thats why .......

**Comment by Faltenreich** [comment]
This is currently not supported due to the logic I described above, but you are free to commit a pull request. As a workaround, you could apply the SkeletonLayout directly to the ViewHolder's View and wrap that inside of a ViewGroup with the desired background.
